config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :galleries do
    resources :images, :only => [:create,:destroy]
  end
  resources :reservation_packages
  resources :parameters
  resources :cities
  resources :package_products
  resources :packages
  resources :package_types
  resources :reservation_products
  resources :product_types
  resources :products
  resources :reservations
  resources :component_actions
  resources :system_actions
  resources :system_components
  resources :components
 devise_for :admins, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register",:edit=>"user_profile" },:controllers => { registrations: 'registrations',sessions:'sessions' }
scope "/users" do
  resources :admins
end
devise_scope :admin do
  get '/logout' => "devise/sessions#destroy"
end
authenticated :admin do
   root 'frontend#index' ,as: :authenticated_root
end

  root 'frontend#index'
  
  resources :user_roles

  resources :user_roles do
  collection do
    post 'create_role_for_user' 
  end
end
 resources :assignments
  resources :roles
  resources :products
  resources :frontend
 
 # Front end Routes
 get '/user_login',to: 'frontend#user_login'
 get '/tours' , to: 'frontend#index'
 get '/dashboard' , to: 'dashboard#index'
 post '/search_tour' , to: 'frontend#search_tour'
 post '/index' , to: 'frontend#tours'
 post '/tours' , to: 'frontend#tours'
 
 get '/search_hotel' , to: 'frontend#search_hotel'
 post '/search_hotel' , to: 'frontend#search_hotel'

 get '/search_package' , to: 'frontend#search_package'
 post '/search_package' , to: 'frontend#search_package'

 get '/reserve_product/:product_id',to: 'frontend#reserve_product'

 get '/all_tours' , to: 'frontend#all_tours'
 get '/all_hotels' , to: 'frontend#all_hotels'
 get '/all_flights' , to: 'frontend#all_flights'
 get '/all_packages' , to: 'frontend#all_packages'
 get '/all_shuttles' , to: 'frontend#all_shuttles'
 get '/contact_us' , to: 'frontend#contact_us'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Reservations--------------
  post '/add_product_temp' , to: 'reservation#add_product_temp'
 
  #-------------------------
  resources :users
  get 'goodbye', to: 'application#goodbye'
  
  resources :articles do
    resources :comments
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 has_many :assignments
 has_many :roles, through: :assignments
 validates :name, presence: true
#validates :name ,presence: true

def role?(role)
  roles.any? { |r| r.role.underscore.to_sym == role }
end

def multiple_role?(permited_roles)
  
   permited_roles.each {|pr|
    if  roles.any? { |r| r.role == pr}
       return  true
   end   
   }
  return false
end
end

app/models/article.rb
class Article < ApplicationRecord
 has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :admin
  belongs_to :role
  validates_uniqueness_of :role_id, :scope => :admin_id
end

app/models/city.rb
class City < ApplicationRecord
    belongs_to :country
    validates_uniqueness_of :name, :scope => :country_id
    validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :cities
    validates :name, presence: true,uniqueness: true
    validates :nicename, presence: true,uniqueness: true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    validates :title, presence: true
    mount_uploaders :images, ImageUploader # mount the uploaders
end

app/models/package.rb
class Package < ApplicationRecord
    has_one :package_type
    has_many :package_products
    mount_uploader :image, ImageUploader
    has_many :reservation_packages
    has_many :reservations, through: :reservation_packages
    validates :name, presence: true
    validates :package_type_id, presence: true
end

app/models/package_type.rb
class PackageType < ApplicationRecord
    validates :name, presence: true,uniqueness: true
end

app/models/parameter.rb
class Parameter < ApplicationRecord
  validates_uniqueness_of :name, :scope => :value
  validates :name, presence: true
  validates :value, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :product_type
    has_many :package_products
    has_many :reservation_products
    has_many :reservations, through: :reservation_products
    mount_uploader :image, ImageUploader
    validates :name, presence: true
    validates :price, presence: true
    validates :product_type_id, presence: true
end

app/models/product_type.rb
class ProductType < ApplicationRecord
has_one :product
validates :name, presence: true,uniqueness: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    has_many :reservation_products
    has_many :products, through: :reservation_products
    validates :client_id, presence: true
    validates :status, presence: true
    validates :number_kids, presence: true
    validates :number_adults, presence: true
    attr_accessor :is_front_end
    attr_accessor :product_id
    
end

app/models/role.rb
class Role < ApplicationRecord
   has_many :assignments
   has_many :admins, through: :assignments 
   validates :role, presence: true,uniqueness: true
end

app/models/system_action.rb
class SystemAction < ApplicationRecord
     validates :action, presence: true,uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_roles, dependent: :destroy
    validates :name,:password,:email, presence: true
    validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :role
  belongs_to :user
  validates_uniqueness_of :role_id, :scope => :user_id
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
<%= form_for(admin) do |f| %>
   <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      
      </ul>
    </div>
  <% end %>

  <% if flash[:warning]%>
  <div class="alert alert-danger alert-dismissable">
  <i class="fa fa-ban"></i>
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <b><%= flash[:warning] %></b>
  </div>
 <% end %>
  <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name ,class:"form-control" %>
   </div>  
  
  <div class="form-group">
      <%= f.label :nickname %><br />
      <%= f.text_field :nickname ,class:"form-control" %>
   </div>  
   <div class="form-group">
      <%= f.label :email %><br />
      <%= f.text_field :email ,class:"form-control" %>
   </div>   

   <div class="form-group">  
      <%= f.label :password %><% if params[:action]=="edit" %> <i>(leave blank if you don't want to change it)</i><%end %><br />
      <%= f.password_field :password ,class:"form-control" %>
   </div>

   <div class="form-group">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation ,class:"form-control" %>
   </div>


   <div class="actions">
        <%= link_to 'Cancel', admins_path ,class:"btn btn-danger"%> <%= f.submit "Save" ,class:"btn btn-primary" %> 
   </div>

<% end %>

app/views/admins/edit.html.erb
<h3>Editing Admin</h3>

<%= render 'form', admin: @admin %>

app/views/admins/index.html.erb
<h3>Admin Users</h3>
<%= link_to '<i class="fa fa-plus-square" aria-hidden="true"></i>  New User'.html_safe,new_admin_path ,class:"btn btn-success"%>
<hr></hr>
<table id="admin_user_list">
  <thead>
    <tr>
      <th>Name</th>
      <th>Nickname</th>
      <th>Email</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
      <td><%= admin.name %></td>
        <td><%= admin.nickname %></td>
        <td><%= admin.email %></td>
        <td><%= link_to '<i class="fa fa-pencil-square-o"></i> Edit'.html_safe, edit_admin_path(admin) ,class:"btn btn-info"%></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i> Delete'.html_safe, admin, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-danger"%></td>
      </tr>
    <% end %>

    
  </tbody>
</table>

<br>

app/views/admins/new.html.erb
<h3>New Admin</h3>

<%= render 'form', admin: @admin %>

app/views/admins/show.html.erb
<div class="actions">
<%= link_to '<i class="fa fa-arrow-left"></i> Back'.html_safe, admins_path ,class:"btn btn-info"%>
<%= link_to '<i class="fa fa-pencil-square-o"></i> Edit'.html_safe,  edit_admin_path(@admin),class:"btn btn-info"%>
</div>