config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :galleries do
    resources :images, :only => [:create,:destroy]
  end
  resources :reservation_packages
  resources :parameters
  resources :cities
  resources :package_products
  resources :packages
  resources :package_types
  resources :reservation_products
  resources :product_types
  resources :products
  resources :reservations
  resources :component_actions
  resources :system_actions
  resources :system_components
  resources :components
 devise_for :admins, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register",:edit=>"user_profile" },:controllers => { registrations: 'registrations',sessions:'sessions' }
scope "/users" do
  resources :admins
end
devise_scope :admin do
  get '/logout' => "devise/sessions#destroy"
end
authenticated :admin do
   root 'frontend#index' ,as: :authenticated_root
end

  root 'frontend#index'
  
  resources :user_roles

  resources :user_roles do
  collection do
    post 'create_role_for_user' 
  end
end
 resources :assignments
  resources :roles
  resources :products
  resources :frontend
 
 # Front end Routes
 get '/user_login',to: 'frontend#user_login'
 get '/tours' , to: 'frontend#index'
 get '/dashboard' , to: 'dashboard#index'
 post '/search_tour' , to: 'frontend#search_tour'
 post '/index' , to: 'frontend#tours'
 post '/tours' , to: 'frontend#tours'
 
 get '/search_hotel' , to: 'frontend#search_hotel'
 post '/search_hotel' , to: 'frontend#search_hotel'

 get '/search_package' , to: 'frontend#search_package'
 post '/search_package' , to: 'frontend#search_package'

 get '/reserve_product/:product_id',to: 'frontend#reserve_product'

 get '/all_tours' , to: 'frontend#all_tours'
 get '/all_hotels' , to: 'frontend#all_hotels'
 get '/all_flights' , to: 'frontend#all_flights'
 get '/all_packages' , to: 'frontend#all_packages'
 get '/all_shuttles' , to: 'frontend#all_shuttles'
 get '/contact_us' , to: 'frontend#contact_us'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Reservations--------------
  post '/add_product_temp' , to: 'reservation#add_product_temp'
 
  #-------------------------
  resources :users
  get 'goodbye', to: 'application#goodbye'
  
  resources :articles do
    resources :comments
  end
end

app/controllers/component_actions_controller.rb
class ComponentActionsController < ApplicationController
  before_action :set_component_action, only: [:show, :edit, :update, :destroy,:get_roles_by_actions]

  # GET /component_actions
  # GET /component_actions.json
  def index
      
    @component_actions = ComponentAction.all
  end

  # GET /component_actions/1
  # GET /component_actions/1.json
  def show
    authorize @component_action
  end

  # GET /component_actions/new
  def new
    @component_action = ComponentAction.new
    @role =Role.all
    @system_component=SystemComponent.all
    @system_action =SystemAction.all
    
  end

  # GET /component_actions/1/edit
  def edit
    
    @selected_role=@component_action.role_id
    @selected_system_component=@component_action.system_component_id
    @selected_system_action =@component_action.system_action_id
    @role =Role.all
    @system_component=SystemComponent.all
    @system_action =SystemAction.all
  end

  # POST /component_actions
  # POST /component_actions.json
  def create
    @component_action = ComponentAction.new(component_action_params)
    authorize @component_action
    respond_to do |format|
      if @component_action.save
        format.html { redirect_to @component_action, notice: 'Component action was successfully created.' }
        format.json { render :show, status: :created, location: @component_action }
      else
      
    @role =Role.all
    @system_component=SystemComponent.all
    @system_action =SystemAction.all
    @selected_role=component_action_params[:role_id]
    @selected_system_component=component_action_params[:selected_system_component_id]
    @selected_system_action =component_action_params[:selected_system_action_id]
    
        format.html { render :new }
        format.json { render json: @component_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /component_actions/1
  # PATCH/PUT /component_actions/1.json
  def update
    authorize @component_action
    respond_to do |format|
      if @component_action.update(component_action_params)
        format.html { redirect_to @component_action, notice: 'Component action was successfully updated.' }
        format.json { render :show, status: :ok, location: @component_action }
      else
    @role =Role.all
    @system_component=SystemComponent.all
    @system_action =SystemAction.all
    @selected_role=component_action_params[:role_id]
    @selected_system_component=component_action_params[:selected_system_component_id]
    @selected_system_action =component_action_params[:selected_system_action_id]
        format.html { render :edit }
        format.json { render json: @component_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /component_actions/1
  # DELETE /component_actions/1.json
  def destroy
    authorize @component_action
    @component_action.destroy
    respond_to do |format|
      format.html { redirect_to component_actions_url, notice: 'Component action was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
   def get_roles_by_actions(action_name,component_name)
        @system_action =SystemAction.find_by_action(action_name) 
        @system_component =SystemComponent.find_by_name(component_name)
        @permitted_roles = ComponentAction.select("roles.role as rolename").joins("INNER JOIN roles ON roles.id = component_actions.role_id").where(system_action_id:@system_action.id,system_component_id:@system_component.id)
        @role_list =[]
        @permitted_roles.each do |permitted_role|
            @role_list.push(permitted_role.rolename)
          end
      return @role_list
    end  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_component_action
      @component_action = ComponentAction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def component_action_params
      params.require(:component_action).permit(:system_component_id, :system_action_id, :role_id)
    end

    
end

app/helpers/component_actions_helper.rb
module ComponentActionsHelper
end

app/views/component_actions/_form.html.erb
<%= form_for(component_action) do |f| %>
  <% if component_action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(component_action.errors.count, "error") %> prohibited this component_action from being saved:</h2>

      <ul>
      <% component_action.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <% if flash[:warning]%>
  <div class="alert alert-danger alert-dismissable">
  <i class="fa fa-ban"></i>
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <b><%= flash[:warning] %></b>
  </div>
 <% end %>
  <div class="field">
    <%= f.label :system_component_id %>
     <%= f.collection_select(:system_component_id, @system_component, :id, :name,{:selected => @selected_system_component},class:"form-control") %>
  </div>

  <div class="field">
    <%= f.label :system_action_id %>
    <%= f.collection_select(:system_action_id, @system_action, :id, :action,{:selected => @selected_system_action},class:"form-control") %>
  </div>

  <div class="field">
    <%= f.label :role_id %>
    <%= f.collection_select(:role_id, @role, :id, :role,{:selected => @selected_role},class:"form-control") %>
  </div>

  <div class="actions">
    <%= link_to 'Cancel',component_actions_path,class:"btn btn-danger"%> 
   
    <%= f.submit "Save" ,class:"btn btn-primary" %>
  </div>
<% end %>

app/views/component_actions/edit.html.erb
<h1>Editing Component Action</h1>

<%= render 'form', component_action: @component_action %>

app/views/component_actions/index.html.erb
<h3>Component Actions</h3>
<%= link_to '<i class="fa fa-plus-square" aria-hidden="true"></i>  New'.html_safe,new_component_action_path ,class:"btn btn-success"%>
<hr></hr>

<table id="component_action_list">
  <thead>
    <tr>
      <th>System component</th>
      <th>System action</th>
      <th>Role</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @component_actions.each do |component_action| %>
      <tr>
        <td><%= component_action.system_component.name %></td>
        <td><%= component_action.system_action.action %></td>
        <td><%= component_action.role.role %></td>
        <td><%= link_to '<i class="fa fa-search"></i> Show'.html_safe, component_action ,class:"btn btn-default" %></td>
        <td><%= link_to '<i class="fa fa-pencil-square-o"></i> Edit'.html_safe, edit_component_action_path(component_action),class:"btn btn-info" %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i> Delete'.html_safe, component_action, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/component_actions/new.html.erb
<h1>New Component Action</h1>

<%= render 'form', component_action: @component_action %>

app/views/component_actions/show.html.erb
<h3>Component Actions Details</h3>
<hr></hr>

<div class="form-group">
  <strong>System component:</strong>
  <%= @component_action.system_component.name %>
</div>

<div class="form-group">
  <strong>System action:</strong>
  <%= @component_action.system_action.action %>
</div>

<div class="form-group">
  <strong>Role:</strong>
  <%= @component_action.role.role %>
</div>

<div class="actions">
<%= link_to '<i class="fa fa-arrow-left"></i> Back'.html_safe, component_actions_path ,class:"btn btn-info"%>
<%= link_to '<i class="fa fa-pencil-square-o"></i> Edit'.html_safe, edit_component_action_path(@component_action) ,class:"btn btn-info"%>

</div>